services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/code-challenge-bff
      - JWT_ACCESS_TOKEN_SECRET=your-super-secret-access-token-key
      - JWT_REFRESH_TOKEN_SECRET=your-super-secret-refresh-token-key
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: